name: bigbro-cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build and push
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }} \
            -t ${{ secrets.DOCKER_USERNAME }}/bigbro_company-client:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/bigbro_company-client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_IP }}
          port: 22
          username: ubuntu
          key: ${{ secrets.SSH_PEM_KEY }}
          script: |
            set -e
            cd /home/ubuntu/app

            docker pull ${{secrets.DOCKER_USERNAME}}/bigbro_company-client:latest

            if [ "$(docker ps -q -f name=bigbro_company-client-blue)" ]; then
              NEW_COLOR=green
              OLD_COLOR=blue
              NEW_PORT=3001
              OLD_PORT=3000
            else
              NEW_COLOR=blue
              OLD_COLOR=green
              NEW_PORT=3000
              OLD_PORT=3001
            fi

            docker run -d \
              --name bigbro_company-client-${NEW_COLOR} \
              -p ${NEW_PORT}:${NEW_PORT} \
              -e NEXT_PUBLIC_API_BASE_URL=${{secrets.NEXT_PUBLIC_API_BASE_URL}} \
              ${{secrets.DOCKER_USERNAME}}/bigbro_company-client:latest

            docker stop bigbro_company-client-${OLD_COLOR} || true
            docker rm bigbro_company-client-${OLD_COLOR} || true

      - name: Success Discord Notification
        uses: sarisia/actions-status-discord@v1.11.0
        if: success()
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          title: '✅ BIGBRO_CLIENT CD'
          status: ${{ job.status }}
          content: '배포가 완료되었습니다.'
          username: BIGBRO_CLIENT bot

      - name: Failure notification to discord
        uses: sarisia/actions-status-discord@v1.11.0
        if: failure()
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          title: '❌ BIGBRO_CLIENT CD'
          content: '배포에 실패했습니다.'
          status: ${{ job.status }}
          username: BIGBRO_CLIENT bot
