name: bigbro-cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build and push
        run: |
          docker build \
          --build-arg NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }} \
          --build-arg NEXT_PUBLIC_KAKAO_LOGIN_URL=${{ secrets.NEXT_PUBLIC_KAKAO_LOGIN_URL }} \-t ${{secrets.DOCKER_USERNAME}}/bigbro_client:latest .
          docker push ${{secrets.DOCKER_USERNAME}}/bigbro_client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create SSH key
        run: |
          echo "${{ secrets.SSH_PEM_KEY }}" > SSH_PEM_KEY.pem
          chmod 600 SSH_PEM_KEY.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "SSH_PEM_KEY.pem" ubuntu@${{secrets.EC2_IP}} << EOF
            cd /home/ubuntu/app
            docker pull ${{secrets.DOCKER_USERNAME}}/bigbro_client:latest
            docker run -d \
              --name bigbro_client \
              -p 3000:3000 \
              -e NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }} \
              -e NEXT_PUBLIC_KAKAO_LOGIN_URL=${{ secrets.NEXT_PUBLIC_KAKAO_LOGIN_URL }} \
              ${{secrets.DOCKER_USERNAME}}/bigbro_client:latest
          EOF

      - name: Success Discord Notification
        uses: sarisia/actions-status-discord@v1.11.0
        if: success()
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          title: '✅ BIGBRO_CLIENT CD'
          status: ${{ job.status }}
          content: '배포가 완료되었습니다.'
          username: BIGBRO_CLIENT bot

      - name: Failure notification to discord
        uses: sarisia/actions-status-discord@v1.11.0
        if: failure()
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          title: '❌ BIGBRO_CLIENT CD'
          content: '배포에 실패했습니다.'
          status: ${{ job.status }}
          username: BIGBRO_CLIENT bot
